version: "3"

services:
  django_news_api:
    build:
      context: .

    ports:
      - "8000:8000"

    volumes:
      - .:/django_news_api

    command: sh -c "python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=posts
      - DB_USER=userdb
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=posts
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=password